EXPLORATORY DATA ANALYSIS

In [ ]:
#Data Manipulation
import pandas as pd
import numpy as np

In [ ]:
#Data Visualization
import matplotlib.pyplot as plt

In [ ]:
#NLP
import nltk

In [ ]:
#Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Loading the dataset
df = pd.read_csv("../data/employee_reviews.csv")

In [ ]:
df.head()

,Unnamed: 0,company,location,dates,job-title,summary,pros,cons,advice-to-mgmt,overall-ratings,work-balance-stars,culture-values-stars,carrer-opportunities-stars,comp-benefit-stars,senior-mangemnet-stars,helpful-count,link
0,1,google,none,"Dec 11, 2018",Current Employee - Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,none,5.0,4.0,5.0,5.0,4.0,5.0,0,https://www.glassdoor.com/Reviews/Google-Revie...
1,2,google,"Mountain View, CA","Jun 21, 2013",Former Employee - Program Manager,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,4.0,2.0,3.0,3.0,5.0,3.0,2094,https://www.glassdoor.com/Reviews/Google-Revie...
2,3,google,"New York, NY","May 10, 2014",Current Employee - Software Engineer III,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,5.0,4.0,5.0,5.0,4.0,949,https://www.glassdoor.com/Reviews/Google-Revie...
3,4,google,"Mountain View, CA","Feb 8, 2015",Current Employee - Anonymous Employee,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,5.0,2.0,5.0,5.0,4.0,5.0,498,https://www.glassdoor.com/Reviews/Google-Revie...
4,5,google,"Los Angeles, CA","Jul 19, 2018",Former Employee - Software Engineer,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...",Promote managers into management for their man...,5.0,5.0,5.0,5.0,5.0,5.0,49,https://www.glassdoor.com/Reviews/Google-Revie...

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 67529 entries, 0 to 67528
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  67529 non-null  int64
 1   company                     67529 non-null  str
 2   location                    67529 non-null  str
 3   dates                       67528 non-null  str
 4   job-title                   67529 non-null  str
 5   summary                     67402 non-null  str
 6   pros                        67529 non-null  str
 7   cons                        67529 non-null  str
 8   advice-to-mgmt              66857 non-null  str
 9   overall-ratings             67529 non-null  float64
 10  work-balance-stars          67529 non-null  str
 11  culture-values-stars        67529 non-null  str
 12  carrer-opportunities-stars  67529 non-null  str
 13  comp-benefit-stars          67529 non-null  str
 14  senior-mangemnet-stars      67529 non-null  str
 15  helpful-count               67529 non-null  int64
 16  link                        67529 non-null  str
dtypes: float64(1), int64(2), str(14)
memory usage: 44.4 MB

In [ ]:
df.describe()

         Unnamed: 0  overall-ratings  helpful-count
count  67529.000000     67529.000000   67529.000000
mean   33765.000000         3.826075       1.268211
std    19494.087501         1.154989      16.085852
min        1.000000         1.000000       0.000000
25%    16883.000000         3.000000       0.000000
50%    33765.000000         4.000000       0.000000
75%    50647.000000         5.000000       1.000000
max    67529.000000         5.000000    2094.000000

In [ ]:
df.isnull().sum()

Unnamed: 0                      0
company                         0
location                        0
dates                           1
job-title                       0
summary                       127
pros                            0
cons                            0
advice-to-mgmt                672
overall-ratings                 0
work-balance-stars              0
culture-values-stars            0
carrer-opportunities-stars      0
comp-benefit-stars              0
senior-mangemnet-stars          0
helpful-count                   0
link                            0
dtype: int64

PREPROCESSING

In [ ]:
df = df[['summary','pros','cons','overall-ratings']]

In [ ]:
df['summary'] = df['summary'].fillna('')

In [ ]:
df['summary'].isnull().sum()

np.int64(0)

In [ ]:
# Combine all text into one review
df['review'] = (
    df['summary'] + " " +
    df['pros'] + " " +
    df['cons']
)

In [ ]:
df[['summary', 'pros', 'cons', 'review']].head()

,summary,pros,cons,review
0,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,Best Company to work for People are smart and ...
1,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,"Moving at the speed of light, burn out is inev..."
2,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Great balance between big-company security and...
3,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,The best place I've worked and also the most d...
4,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...","Unique, one of a kind dream job Google is a wo..."

In [ ]:
df[['summary', 'pros', 'cons', 'review']].head()

,summary,pros,cons,review
0,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,Best Company to work for People are smart and ...
1,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,"Moving at the speed of light, burn out is inev..."
2,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Great balance between big-company security and...
3,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,The best place I've worked and also the most d...
4,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...","Unique, one of a kind dream job Google is a wo..."

In [ ]:
df['review'].head()

0    Best Company to work for People are smart and ...
1    Moving at the speed of light, burn out is inev...
2    Great balance between big-company security and...
3    The best place I've worked and also the most d...
4    Unique, one of a kind dream job Google is a wo...
Name: review, dtype: str

In [ ]:
def get_sentiment(rating):
    if rating >= 4:
        return 'Positive'
    elif rating == 3:
        return 'Neutral'
    else:
        return 'Negative'

In [ ]:
df['sentiment'] = df['overall-ratings'].apply(get_sentiment)

In [ ]:
df[['overall-ratings', 'sentiment']].head(10)

   overall-ratings sentiment
0              5.0  Positive
1              4.0  Positive
2              5.0  Positive
3              5.0  Positive
4              5.0  Positive
5              5.0  Positive
6              5.0  Positive
7              5.0  Positive
8              5.0  Positive
9              5.0  Positive

In [ ]:
df['sentiment'].value_counts()

sentiment
Positive    45688
Neutral     12653
Negative     9188
Name: count, dtype: int64

Text Preprocessing

In [ ]:
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to C:\Users\Areesha
[nltk_data]     Batool\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Areesha
[nltk_data]     Batool\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Areesha
[nltk_data]     Batool\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Areesha
[nltk_data]     Batool\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [63]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)

    # Tokenize
    words =text.split()

    # Remove stopwords
    words = [word for word in words if word not in stop_words]

    # Lemmatize
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [64]:
df["clean_review"] = df["review"].apply(clean_text)

In [65]:
df[['review', 'clean_review']].head()

,review,clean_review
0,Best Company to work for People are smart and ...,best company work people smart friendly bureau...
1,"Moving at the speed of light, burn out is inev...",moving speed light burn inevitable 1 food food...
2,Great balance between big-company security and...,great balance bigcompany security fun fastmovi...
3,The best place I've worked and also the most d...,best place ive worked also demanding cant find...
4,"Unique, one of a kind dream job Google is a wo...",unique one kind dream job google world every c...

Feature Engineering (TF-IDF Vectorization)

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [71]:
tfidf = TfidfVectorizer(max_features=5000)

In [72]:
X = tfidf.fit_transform(df["clean_review"])

In [73]:
y = df["sentiment"]

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Train Logistic Regression Model

In [94]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [95]:
y_pred = model.predict(X_test)

Model Evaluation

In [96]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6446023989338072

Classification Report:

              precision    recall  f1-score   support

    Negative       0.48      0.65      0.55      1903
     Neutral       0.31      0.44      0.36      2538
    Positive       0.87      0.70      0.77      9065

    accuracy                           0.64     13506
   macro avg       0.55      0.60      0.56     13506
weighted avg       0.71      0.64      0.67     13506


Confusion Matrix:

[[1232  483  188]
 [ 620 1120  798]
 [ 699 2012 6354]]

SAVE THE MODEL

In [97]:
import joblib

In [98]:
import os

os.makedirs("models", exist_ok=True)

In [99]:
joblib.dump(model, "models/logistic_model.pkl")
joblib.dump(tfidf, "models/tfidf_vectorizer.pkl")

['models/tfidf_vectorizer.pkl']

In [100]:
df["sentiment"].value_counts()

sentiment
Positive    45688
Neutral     12653
Negative     9188
Name: count, dtype: int64